### ISSUE TITLE
Crash with comfyui-profiler

### ISSUE THREAD

**Issue by CameronWDMorgan** [tzwm/comfyui-profiler#8]
[profiler] #142 PreviewImage: 0.2367 seconds, total 13.0739 seconds(#141)
[profiler] #64 SaveImage: 0.4078 seconds, total 13.245 seconds(#141)
Prompt executed in 13.51 seconds
[rgthree] Using rgthree's optimized recursive execution.
Traceback (most recent call last):
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\main.py", line 254, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\main.py", line 149, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\server.py", line 622, in publish_loop
    await self.send(*msg)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\server.py", line 557, in send
    await self.send_json(event, data, sid)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\server.py", line 608, in send_json
    await send_socket_catch_exception(ws.send_json, message)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\server.py", line 36, in send_socket_catch_exception
    await function(message)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_ws.py", line 351, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_ws.py", line 335, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\http_websocket.py", line 644, in _send_frame
    message = await compressobj.compress(message)
  File "C:\Users\anime\Documents\Coding\Stability Matrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\compression_utils.py", line 71, in compress
    async with self._compress_lock:
  File "asyncio\locks.py", line 14, in __aenter__
  File "asyncio\locks.py", line 106, in acquire
  File "asyncio\mixins.py", line 30, in _get_loop
RuntimeError: <asyncio.locks.Lock object at 0x000001F21C304760 [unlocked, waiters:1]> is bound to a different event loop

**Comment by devesch** [comment]
THE SAME HERE!!

Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/main.py", line 254, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "/opt/conda/envs/pytorch/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/ComfyUI/main.py", line 149, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "/home/ubuntu/ComfyUI/server.py", line 635, in publish_loop
    await self.send(*msg)
  File "/home/ubuntu/ComfyUI/server.py", line 570, in send
    await self.send_json(event, data, sid)
  File "/home/ubuntu/ComfyUI/server.py", line 621, in send_json
    await send_socket_catch_exception(ws.send_json, message)
  File "/home/ubuntu/ComfyUI/server.py", line 36, in send_socket_catch_exception
    await function(message)
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/aiohttp/web_ws.py", line 351, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/aiohttp/web_ws.py", line 335, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 644, in _send_frame
    message = await compressobj.compress(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/pytorch/lib/python3.11/site-packages/aiohttp/compression_utils.py", line 71, in compress
    async with self._compress_lock:
  File "/opt/conda/envs/pytorch/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/opt/conda/envs/pytorch/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/pytorch/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x7fb78fcc6910 [unlocked, waiters:1]> is bound to a different event loop
